
const rowsDashboard = [
    {
        id: 1,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 2,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Unsuccessful',
    },
    {
        id: 3,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Checking',
    },
    {
        id: 4,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 5,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 6,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 7,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 8,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 9,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 10,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 11,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 12,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 13,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 14,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 15,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 16,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 17,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 18,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 19,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 20,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 21,
        from: 'USDT',
        to: 'PM',
        amount: 1000,
        received: 1200,
        date: '25-02-2023',
        status: 'Successful',
    },
];
const rowsPartner = [
    {
        id: 1,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 2,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Unsuccessful',
    },
    {
        id: 3,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Checking',
    },
    {
        id: 4,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 5,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 6,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Checking',
    },
    {
        id: 7,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Unsuccessful',
    },
    {
        id: 8,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Checking',
    },
    {
        id: 9,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 10,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 11,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Checking',
    },
    {
        id: 12,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Unsuccessful',
    },
    {
        id: 13,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Checking',
    },
    {
        id: 14,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 15,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 16,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Unsuccessful',
    },
    {
        id: 17,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Checking',
    },
    {
        id: 18,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Unsuccessful',
    },
    {
        id: 19,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Successful',
    },
    {
        id: 20,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Checking',
    },
    {
        id: 21,
        to: 'x09aa998ee454c456255daf3ac94908f1dcfb7033',
        from: 'USDT',
        date: '25-02-2023',
        status: 'Checking',
    },
   
];

const FAQArray = [
    {
        id: 1,
        question: 'How to Complete Identity Verification for a Personal Account?',
        answer: 'You can access the identity verification from [Account] - [Identification], or click [Verify] / [Get verified] from the homepage banners. You can check your current verification level on the page, which determines the trading limit of your account. To increase your limit, please complete the respective identity verification level.'
    },
    {
        id: 2,
        question: 'How to complete identity verification for a personal account on the pmusdt website?',
        answer: 'You can access the identity verification from [Account] - [Identification], or click [Verify] / [Get verified] from the homepage banners. You can check your current verification level on the page, which determines the trading limit of your account. To increase your limit, please complete the respective identity verification level.'
    },
    {
        id: 3,
        question: 'How to complete identity verification for a personal account on the pmusdt website?',
        answer: 'You can access the identity verification from [Account] - [Identification], or click [Verify] / [Get verified] from the homepage banners. You can check your current verification level on the page, which determines the trading limit of your account. To increase your limit, please complete the respective identity verification level.'
    },
    {
        id: 4,
        question: 'How to complete identity verification for a personal account on the pmusdt website?',
        answer: 'You can access the identity verification from [Account] - [Identification], or click [Verify] / [Get verified] from the homepage banners. You can check your current verification level on the page, which determines the trading limit of your account. To increase your limit, please complete the respective identity verification level.'
    },
    {
        id: 5,
        question: 'How to complete identity verification for a personal account on the pmusdt website?',
        answer: 'You can access the identity verification from [Account] - [Identification], or click [Verify] / [Get verified] from the homepage banners. You can check your current verification level on the page, which determines the trading limit of your account. To increase your limit, please complete the respective identity verification level.'
    },
    {
        id: 6,
        question: 'How to complete identity verification for a personal account on the pmusdt website?',
        answer: 'You can access the identity verification from [Account] - [Identification], or click [Verify] / [Get verified] from the homepage banners. You can check your current verification level on the page, which determines the trading limit of your account. To increase your limit, please complete the respective identity verification level.'
    },
    {
        id: 7,
        question: 'How to complete identity verification for a personal account on the pmusdt website?',
        answer: 'You can access the identity verification from [Account] - [Identification], or click [Verify] / [Get verified] from the homepage banners. You can check your current verification level on the page, which determines the trading limit of your account. To increase your limit, please complete the respective identity verification level.'
    },
    {
        id: 8,
        question: 'How to complete identity verification for a personal account on the pmusdt website?',
        answer: 'You can access the identity verification from [Account] - [Identification], or click [Verify] / [Get verified] from the homepage banners. You can check your current verification level on the page, which determines the trading limit of your account. To increase your limit, please complete the respective identity verification level.'
    },
]

const conditions = [
    'any change in exchange rate on the binance exchange gives us the right to recalculate the amount of the application.',
    'the rate for your application will be fixed after 1 confirmation online.',
    'funds are credited after 20 transaction confirmations.',
    'we conduct AML checks in accordance with the AML policy of the flashobmen service.',
    'fill out all fields of the form provided.',
    'click the “make an exchange” button.',
    'read the terms of exchange. if you accept them, check the approprite boxes9. pay for the application according to the instructions on the website.'
]

const inputSuccesData = [
    {
        id: '1',
        labelTitle: 'e- voucher :',
        inputValue: '2326564925',
    },
    {
        id: '2',
        labelTitle: 'activation code :',
        inputValue: '9012037427092330',
    },
    {
        id: '3',
        labelTitle: 'amount :',
        inputValue: '100 USDT',
    },
    {
        id: '4',
        labelTitle: 'time & date :',
        inputValue: '25-02-2023, 13:22:16',
    },
   
]

export {rowsDashboard, rowsPartner, FAQArray, conditions, inputSuccesData}